server:
  #端口号
  port: 85
  servlet:
    encoding:
      #编码
      charset: UTF-8
    context-path: /ww
spring:
  jackson:
    #Json时间格式
    time-format: yyyy-MM-dd
  mvc:
    format:
      date: yyyy-MM-dd
  #页面缓存
  thymeleaf:
    cache: false
    #数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.88:3306/sb1
    username: root
    password: Abcd1234$
#调试模式
debug: false
